# Jupyter Book settings

title: git
author: Thierry Parmentelat
logo: media/logo-git-square.svg

repository:
  url: https://github.com/ue12-p21/git
  branch: main
  path_to_book: notebooks

html:
  use_repository_button: yes
  use_edit_page_button: yes
  use_issues_button: yes
#  use_multitoc_numbering: true

###

only_build_toc_files: true

execute:
#  execute_notebooks: "force"
  execute_notebooks: cache

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent
#    extensions:
#    - "sphinxcontrib.video"

# for raw <img> tags in markdown
parse:
  myst_enable_extensions:
    - html_image
